### PR TITLE
Api 7629 add caregiver support service

### PR DESCRIPTION
**Pull request by taylorrassmannlibertyits**
https://vajira.max.gov/browse/API-7629
Added `CaregiverSupport` to a facility's service list if VHA facility is located in stored file during reload.

Note this was branched off the java 16 upgrade branch, so that needs to be merged first.

### CODE REVIEW

**Comment by taylorrassmannlibertyits** [comment]
I mixed up pom versioning on the merge. Stand by for update.

**Comment by jnguy-va** [comment]
Local tests look good, filtering and etc.
i.e. 
- http://localhost:8085/v0/facilities?state=IN&type=health&services[]=CaregiverSupport
- http://localhost:8085/v0/facilities?state=FL&services[]=CaregiverSupport

Pending the POM fix above for approval

**Review by jnguy-va — APPROVED** [review]

**Review by as-va — CHANGES_REQUESTED** [review]
There is no testing for the new feature here. It looks like you added tests for unrelated functions just to get coverage up since the new code is not covered by tests. Why not add some test cases for verifying test facilities do/do-not have the new service?

**Comment by taylorrassmannlibertyits** [comment]
> There is no testing for the new feature here. It looks like you added tests for unrelated functions just to get coverage up since the new code is not covered by tests. Why not add some test cases for verifying test facilities do/do-not have the new service?

Just did what the other code did for websites. (not that that is ok). I'll look into adding a test for this. The coverage was the issue, and the current tests go through the flow of the newly added code.

**Review by as-va — APPROVED** [review]

**Pull request merged**
