### PR TITLE
Provide ability to filter for mobile sites

### PR DESCRIPTION
**Pull request by taylorrassmannlibertyits**
https://vajira.max.gov/browse/API-3320
Added the ability to filter on 'mobile' sites for facilities searches

### CODE REVIEW

**Comment by taylorrassmannlibertyits** [comment]
Stand by, there are issues with mobile site filtering and descriptions need updating as well @as-va @jnguy-va

**Comment by taylorrassmannlibertyits** [comment]
> Stand by, there are issues with mobile site filtering and descriptions need updating as well @as-va @jnguy-va

Testing completed, just need to update descriptions

**Comment by taylorrassmannlibertyits** [comment]
> > Stand by, there are issues with mobile site filtering and descriptions need updating as well @as-va @jnguy-va
> 
> Testing completed, just need to update descriptions

Descriptions updated! All should be good to review.

**Comment by taylorrassmannlibertyits** [comment]
@darduda Could you take a look at the descriptions updates for `mobile` searches?

**Comment by darduda** [comment]
Reviewed and made some small adjustments to commas. Otherwise, looks good.

**Comment by taylorrassmannlibertyits** [comment]
> Reviewed and made some small adjustments to commas. Otherwise, looks good.

Excellent, thanks @darduda !

**Comment by jnguy-va** [comment]
Builds without issue and calls look good!

Do we want to a few IT tests for mobile?  I.e. in _SearchIT.java_ like `searchByZipWithMobile()`, `searchByStateWithMobile()`, `searchBySstateWithTypeAndMobile()`, etc.

**Comment by taylorrassmannlibertyits** [comment]
> Builds without issue and calls look good!
> 
> Do we want to a few IT tests for mobile? I.e. in _SearchIT.java_ like `searchByZipWithMobile()`, `searchByStateWithMobile()`, `searchByStateWithTypeAndMobile()`, etc.

While those searches aren't explicitly called out, they are processed in a few of the tests in this PR.

**Review by as-va — APPROVED** [review]

**Pull request merged**
