### PR TITLE
F: Use national.xml as the primary source for cemetery names

### PR DESCRIPTION
**Pull request by taylorrassmannlibertyits**
Updated to prioritize national xml facility name and website information.
https://vajira.max.gov/browse/API-5023

### CODE REVIEW

**Comment by as-va** [comment]
Are you aware you have test failures in this branch?

    Error:  Failures: 
    Error:    InternalFacilitiesControllerTest.collect_createUpdate:166 

[Log](https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/197/checks?check_run_id=1921864298#step:6:4059)

**Comment by taylorrassmannlibertyits** [comment]
> Are you aware you have test failures in this branch?
> 
> ```
> Error:  Failures: 
> Error:    InternalFacilitiesControllerTest.collect_createUpdate:166 
> ```
> 
> [Log](https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/197/checks?check_run_id=1921864298#step:6:4059)

No I was not! I'll investigate

**Comment by jnguy-va** [comment]
I'm getting that `http://localhost:8085/v0/facilities/nca_089` is not found?  From the note in JIRA.

**Comment by taylorrassmannlibertyits** [comment]
> I'm getting that `http://localhost:8085/v0/facilities/nca_089` is not found? From the note in JIRA. Did a reload.

That's not from the national.xml file, but cdw

**Review by jnguy-va — APPROVED** [review]
Looks good from my end, remember to test the CDW facility when merged to QA.

Will do any other retests if code changes go in.

**Review by as-va — APPROVED** [review]

**Pull request merged**
