### PR TITLE
API-6878 Add swagger verbiage around 429 error

### PR DESCRIPTION
**Pull request by jnguy-va**
https://vajira.max.gov/browse/API-6878

Added in 429 swagger documentation for the API.

After team approval will need UX approval and acceptance from Bryan + Dave Mazik/James Costa

### CODE REVIEW

**Review by taylorrassmannlibertyits — APPROVED** [review]

**Review by mviterna — COMMENTED** [review]
Will the response body show up like this? 

{
    "message": "API rate limit exceeded"
}

That's what we have for Forms API

**Comment by jnguy-va** [comment]
I was following [API-6809](https://vajira.max.gov/browse/API-6809) that was used to clone this current story.  The story says:

> In the responses section, add code 429 with description "Exceeds the rate limit for this environment"

And so the openapi.json outputs this:
image

@mviterna Was the new wording `"API rate limit exceeded"` something that came back from further feedback?

**Comment by jnguy-va** [comment]
Looks like a change will be put in to match Forms API per [this Slack thread](https://lighthouseva.slack.com/archives/CDBQ9LN3F/p1620836234064100?thread_ts=1620762368.062200&cid=CDBQ9LN3F)

**Comment by taylorrassmannlibertyits** [comment]
These changes look good, but does this actually modify our API response? Or just the swagger documentation?

**Comment by jnguy-va** [comment]
The changes are to document and match what Kong returns for the 429 error.  [Long Slack thread if you're curious.](https://lighthouseva.slack.com/archives/C018DRXSGUD/p1620241461047700?thread_ts=1620222046.029100&cid=C018DRXSGUD)

**Review by as-va — APPROVED** [review]

**Pull request merged**
